dist: trusty
language: node_js
node_js:
- "stable"
cache:
   directories:
   - node_modules
   - ~/.cache
before_script:
- npm install -g httpserver
- npm install cypress --save-dev
- npm run build
- cd dist && httpserver -p 8080 &
script:
- npm run test
