dist: trusty
language: node_js
node_js:
- 8.12.0
before_script:
- npm run build
- npm run start &
script:
- npx cypress run
deploy:
  provider: firebase
  token:
    secure: "jutK9XPNBs6NIMtSUP5svtEW3bjra/ebw/e0HkBusxcv749rw42UIU0DNIxHXSdchxrgY4AAg1XqhYz+42F2wtdmJ9yVSn6N2l07HVJN0o0v1X9Qc464/P9augMFUz4xT40+8az6nxPsHB0GWmPTICU7nHyzU34xUPlPbNEkoMYlYuJ4VhuW7R/dyRW3c7PGiuii00oNOwDlmHRoWrMUb6T5mYOkSW+hNAesQSiZ0f9b7oMTXvS84dZxwywPD42ZObMlfkGTwKXYxLIB61SnjFcXa4EBxn7LpzXka4d3RZwTwicYZPKV9C6D4XZ2D179Fk70shgIYR0VvQyoA0gUe+iXxxSnQrUekoeCwDjBe9yUKeO7pxwJcJoquWFPY0u0q99wL1UCk428e5B69r3S1VSS2sNaVg5vYzmvWSZUyum0zuLM5l2dpLrJXE+5b/Lp5ATxBA5cu3TnJYJC01amYbRy/Udq2i0ziF8fGNPuPiJ/ITQSACt1nLGHnzMABvnpthuae6VJU7nikCwKXDIUnNqJ2tBJIGphrClJgx1KLSoKLGVUAXEsPBlUtMrYzNA09RCpFlCmD19EUuLnigU9PTu6ZTuIz5CxpOpeDmLrnJuvtjD6klMndTVf+fJvaZNmSYAiA2h0VYM/Xkke8ppOHCvnvRvNIk0OlQQAtjOCRHI="
  skip_cleanup: true
  on:
     branch: master
