dist: trusty
language: node_js
node_js:
- 8.12.0
before_script:
- npm run build
- npm run start &
script:
- npx cypress run
deploy:
  provider: firebase
  token:
    secure: "leOUICSggmpK0iUQQSNlLf6vhNRD269TYejcGFCG8YEKT842a53x480KOtv+j7cE2E8KOvs70L+h6DmtfvkDE0bpemRwSWHxR1Gn6IjWD1++lXbJoGgSvlLxgotkIPaqeCwINBZeuYfFaskxyI2zIlExXv78i4wlBzRv9bImI53UXKcqyEQ+Vqk35kSsDKyVeQ86C/+LRgl9zmAnRBAG7G/JMb7M0ZBD/VJDSarFib/qawHRKc1hTgiNp96KJRSQg7OlcFg7VCRYeLr9QnZAbQQoAHSxaJJIOY7lX6+V6ldBXnjcRh01UCs6wp3yNXqJO1Kh9cXCPoXYCAT4E2yBnhpSdoUcROycsvyMwGKLd+eI8rd1NcVI7L/0ySmEDSLEQ92Wib6CeWlbdoPPjVzIs/gLP01UYlD5e4YOMMl1tlFPbS2B9ZRYVMrxynIflRqp8cyW6HE0vIf7kchqRbOPV9uO5CZmfDCnmohc13gYXkxyE9T9LsvcfeTX1e760B73mIfFC+rlY2dNedK3jBxMZIRqH4O+GhMMuTYatajUg13ddG0UREd94dIiO8wgdA6kxjLUPd7pQ7gU/VtlAWNMB4e38EoK1LJ5r3hAvqPV+LuG0ClppcYmk12aEDjuQ5jtLwnuJINJp4p2PJkb68KFdSSJVE3WCGoOsUwnXmoVrF4="
  skip_cleanup: true
  on:
     branch: master
