dist: trusty
language: node_js
node_js:
- "stable"
cache:
   directories:
   - node_modules
script:
- npm run build
before_script:
- npm install -g httpserver
- npm install cypress --save-dev
- npm run build
- npm run dev &
script:
- npx cypress run
