dist: trusty
language: node_js
node_js:
- 8.12.0
before_script:
- npm run build
- npm run start &
script:
- npx cypress run
- firebase login
deploy:
  provider: firebase
  skip_cleanup: true
  domain: autoreview-agile.firebaseapp.com
  project: ./dist
  on:
     branch: master
