dist: trusty
language: node_js
node_js:
- 8.12.0
before_script:
- npm run build
- npm run start &
script:
- npx cypress run
deploy:
  provider: firebase
  token:
    secure: "1/4CMcj0FFH80wsrRyQKVV0iKj4f3naMNUR1qRU4xdmgM"
  skip_cleanup: true
  domain: autoreview-agile.firebaseapp.com
  project: ./dist
  on:
     branch: master
