dist: trusty
language: node_js
node_js:
- 8.12.0
before_script:
- npm run build
- npm run start &
script:
- npx cypress run
deploy:
  provider: firebase
  token:
    secure: "Fku96wo30iWtKebsXXTBn687/JqmqFzQ5g/FFvpMdaTwpgWRz6PowRdmtKFt7LW6kVqgaVt364dIY9k7Cs0d4JBTWo3RNDVQW5qIfbAH+O5o+6pmxHED5iWnPx1x5a9TyIwoHalX3+RbCL1B8ab/TvNiWUV8f/DbS23TESmUc0yCcyx73ltBbE6yv2PLLBopZwl/aA2BZDbBVqbfe7yiVdMZscf5agmYbEQ7oo0D4+VC78u6ECSf5C0yeadmWOe3sIFJ5/0j7c3jo/g4zHXlf0ktFnaDEJSWZ+K/mEcGuDNAFqSxYs2dsydEpCeSI4Vp3kVrzYH8MqvHc4Aiss3XF/KQ46O9eBflii2qLWlCHAcEFG/U6WebMK1BRrkkb3ubFtBEM7k7GLaGP6FzlLq0EK4a8fi3Q4x+sgPx+u7i0BoIDleCMzsyiSdKAGTati7g/uvJRf70+sqJfvP8Of9nRBinLCmbr5LN/ZAlcfuutKyzYFKa2RYV0Bxdbr32VEOefxX02qXRvYcYAPeMSEFz9ntyOTqL070pchPbr4h2q5RaO2tDjxDuAD0CjPgJJv3aRMqgwiM5ZvSSCWHKGBfqaE62KjMu5e64nGbEgQDexLb2rJetamV8HmXGUkLqS9Cjc05sqXFpAoEQOjfdGvp+ex7VSdLjLQ/QTvi2QjPJF8c="
  skip_cleanup: true
  on:
     branch: master
