dist: trusty
language: node_js
node_js:
- 8.12.0
before_script:
- npm run build
- npm run start &
script:
- npx cypress run
deploy:
  provider: firebase
  token:
    secure: "1/E0cjFYdSq8aoBbDEsJ_-Q5dAjkWTjDxMGO0MKX-OmIU"
  project: ./dist
